# Generated by Django 4.2.7 on 2024-04-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0009_alter_pagecontent_video_caption2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('Index', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='years.startpage')),
            ],
        ),
    ]
