# Generated by Django 4.2.7 on 2024-03-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0005_pagecontent_count_of_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='font_external_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_external_title', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_internal_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_internal_title', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_test_variable_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_1', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_test_variable_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_2', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_test_variable_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_3', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_test_variable_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_4', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_test_variable_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_5', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_text', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_title', to='years.availablefont'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='font_video_caption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_video_caption', to='years.availablefont'),
        ),
    ]
