# Generated by Django 4.2.7 on 2024-03-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0006_pagecontent_font_external_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='youtube_link2',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube видео 2'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='external_title',
            field=models.CharField(blank=True, max_length=100000000, unique=True, verbose_name='Внешнее название'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='internal_title',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Внутреннее название'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='test_variable_1',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Тестовая переменная 1'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='test_variable_2',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Тестовая переменная 2'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='test_variable_3',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Тестовая переменная 3'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='test_variable_4',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Тестовая переменная 4'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='test_variable_5',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Тестовая переменная 5'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(blank=True, max_length=100000000, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='content1',
            field=models.CharField(max_length=100000000000),
        ),
        migrations.AlterField(
            model_name='startpage',
            name='content2',
            field=models.CharField(max_length=100000000000),
        ),
    ]
