# Generated by Django 4.2.7 on 2024-03-24 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0007_pagecontent_youtube_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='video_caption2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='video_caption3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='youtube_link3',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube видео 2'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_external_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_external_title', to='years.availablefont', verbose_name='Шрифт внешнего названия'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_internal_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_internal_title', to='years.availablefont', verbose_name='Шрифт внутреннего названия'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_test_variable_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_1', to='years.availablefont', verbose_name='Шрифт тестовой переменной 1'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_test_variable_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_2', to='years.availablefont', verbose_name='Шрифт тестовой переменной 2'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_test_variable_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_3', to='years.availablefont', verbose_name='Шрифт тестовой переменной 3'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_test_variable_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_4', to='years.availablefont', verbose_name='Шрифт тестовой переменной 4'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_test_variable_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_test_variable_5', to='years.availablefont', verbose_name='Шрифт тестовой переменной 5'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_text', to='years.availablefont', verbose_name='Шрифт текста'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_title', to='years.availablefont', verbose_name='Шрифт заголовка'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='font_video_caption',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='font_video_caption', to='years.availablefont', verbose_name='Шрифт подписи к видео'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='years.project', verbose_name='Проект'),
        ),
    ]
