# Generated by Django 4.2.7 on 2024-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0008_pagecontent_video_caption2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='video_caption2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео 2'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='video_caption3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео 3'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='youtube_link3',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube видео 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
