# Generated by Django 4.2.7 on 2024-04-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0010_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
