# Generated by Django 4.2.7 on 2024-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0011_gif_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpage',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
