# Generated by Django 4.2.7 on 2024-03-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0002_pagecontent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='page_id',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='years.project'),
        ),
    ]
