# Generated by Django 4.2.7 on 2024-03-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0003_remove_pagecontent_page_id_pagecontent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='video_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись к видео'),
        ),
    ]
