# Generated by Django 4.2.7 on 2024-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('years', '0004_pagecontent_video_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='count_of_galery',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество галерей'),
        ),
    ]
